name: AppointmentService CI/CD

on:
  push:
    paths:
      - 'AppointmentService/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./AppointmentService/AppointmentService.API/AppointmentService.API.csproj

    - name: Build
      run: dotnet build ./AppointmentService/AppointmentService.API/AppointmentService.API.csproj --no-restore

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish ./AppointmentService/AppointmentService.API/AppointmentService.API.csproj -c Release -o ./out

    - name: Deploy with Docker
      run: |
        docker build -t appointmentservice ./AppointmentService
        docker stop appointmentservice || true
        docker rm appointmentservice || true
        docker run -d -p 5000:80 --name appointmentservice appointmentservice
