name: CI - AppointmentService

on:
  push:
    paths:
      - 'Src/Services/AppointmentService/**'
  pull_request:
    paths:
      - 'Src/Services/AppointmentService/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Src/Services/AppointmentService/AppointmentService.API/AppointmentService.API.csproj

      - name: Build
        run: dotnet build Src/Services/AppointmentService/AppointmentService.API/AppointmentService.API.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test Src/Services/AppointmentService/AppointmentService.Tests/AppointmentService.Tests.csproj --no-build
