name: NotificationGateway CI/CD

on:
  push:
    paths:
      - 'NotificationGateway/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - run: dotnet restore ./NotificationGateway/NotificationGateway.csproj
    - run: dotnet build ./NotificationGateway/NotificationGateway.csproj --no-restore
    - run: dotnet publish ./NotificationGateway/NotificationGateway.csproj -c Release -o ./out

    - name: Deploy with Docker
      run: |
        docker build -t notificationgateway ./NotificationGateway
        docker stop notificationgateway || true
        docker rm notificationgateway || true
        docker run -d -p 5002:80 --name notificationgateway notificationgateway
