name: CI - NotificationGateway

on:
  push:
    paths:
      - 'NotificationGateway/**'
      - '.github/workflows/gateway.yml'
  pull_request:
    paths:
      - 'NotificationGateway/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore NotificationGateway/NotificationGateway.csproj

      - name: Build
        run: dotnet build NotificationGateway/NotificationGateway.csproj --no-restore --configuration Release
