name: CI - NotificationService

on:
  push:
    paths:
      - 'NotificationService/**'
      - '.github/workflows/notification.yml'
  pull_request:
    paths:
      - 'NotificationService/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore NotificationService/NotificationService/NotificationService.csproj

      - name: Build
        run: dotnet build NotificationService/NotificationService/NotificationService.csproj --no-restore --configuration Release
