name: UserService CI/CD

on:
  push:
    paths:
      - 'UserService/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - run: dotnet restore ./UserService/UserService.API/UserService.API.csproj
    - run: dotnet build ./UserService/UserService.API/UserService.API.csproj --no-restore
    - run: dotnet test
    - run: dotnet publish ./UserService/UserService.API/UserService.API.csproj -c Release -o ./out

    - name: Deploy with Docker
      run: |
        docker build -t userservice ./UserService
        docker stop userservice || true
        docker rm userservice || true
        docker run -d -p 5001:80 --name userservice userservice
